#!/usr/bin/perl -w

use strict;


die "Usage: $0 <file> <header>\n".
    "Replace header in po(t) file <file> by <header> contants\n"
    if ($#ARGV != 1);

my $temp = `mktemp`; chomp($temp);

open F, $ARGV[0] or die "can't open file: $ARGV[0]\n";
open H, $ARGV[1] or die "can't open header file: $ARGV[1]\n";
open T, "> $temp" or die "can't open temp file: $temp\n";

print T <H>;
close H;

my $skip = 1;
my $comm = ''; # comments to first entry

foreach(<F>){

  if ($skip){
    if ((/^\s*#/)){
      $comm.=$_;
    }
    elsif
      ((/^\s*$/) ||
       (/^\s*msgid\s*\"\"/) ||
       (/^\s*msgstr\s*\"\"/) ||
       (/^\s*\"/)){ 
      $comm = '';
    }
    else {
      print T "\n$comm";
      $skip = 0;
    }
  }

  if (!$skip){
    print T;
  }
}
close F;
close T;

`mv $temp $ARGV[0]`;
