#!/bin/sh

. ./functions

fix_po()
{
    sed -i \
	-n \
	-e "1 r headers/$1" \
	-e '/#:/,$ p' \
	-- $2
}

for l in $LANGLIST; do
    touch "compendium/$l.po"
    msgcat -s "po/$l/"*.po "compendium/$l.po" >"$l-new.po"
    fix_po "$l.header" "$l-new.po"
    mv -f "$l-new.po" "compendium/$l.po"
done
