#!/bin/sh -efu

. shell-error
. ./functions

print_help(){
cat <<EOF

Update dictionary for a single module

Usage: $0 <module directory>

EOF
}


mod_dir="${1:-}"

if [ -z "$mod_dir" ]; then
  print_help 1>&2
  exit 1
fi

make -C "$mod_dir" update-po >/dev/null || fatal "Can't do make update-po in $mod_dir"

pot="$(find "$mod_dir/po" -name '*.pot')"
[ -f "$pot" ] || fatal "Can't find $pot"

name=${pot##*/}
name=${name%.pot}

cp -f "$pot" pot/

echo "Updating dictionary for $name"

for l in $LANGLIST; do
  mod_po="$mod_dir/po/$l.po"
  po="po/$l/$name.po"
  mkdir -p "po/$l"

  if [ ! -f "$po" ]; then
    [ -f "$mod_po" ] && mv "$mod_po" "$po" || touch "$po"
  fi

  msgmerge --update --backup=off \
           --compendium="compendium/$l.po" "$po" "$pot" &>/dev/null ||\
    fatal "Can't do msgmerge for $l language"
done

rm -rf "$mod_dir/po/"


