#!/bin/sh

repoprefix="git.alt"
repolist=modules.list
repodir=repositories
langlist="ru uk"
potfile=alterator.pot

mkdir -p "$repodir"
grep '^[^#]' "$repolist"|
while read repo; do
    mkdir -p "$repodir/${repo%/*}"
    git-clone "$repoprefix:$repo" "$repodir/$repo"
    make -C "$repodir/$repo" update-po ||:
    make -C "$repodir/$repo/${repo##*/}" update-po ||:
done

touch $potfile
for i in $langlist; do touch $i.po; done

msgcat -o $potfile $potfile `find "$repodir" -name '*.pot'`

for i in $langlist; do
    msgcat -o $i.po $i.po `find "$repodir" -name "$i.po"`
done

rm -rf "$repodir"

./headers/po_head_repl alterator.pot ./headers/pot.header
for i in $langlist; do 
  ./headers/po_head_repl $i.po ./headers/$i.header
done

