#!/bin/sh

repoprefix="git.alt"
repolist=modules.list
repodir=repositories
langlist="ru uk"
potfile=alterator.pot

. shell-error

mkdir -p "$repodir"
grep '^[^#]' "$repolist"|
    while read repo; do
	mkdir -p "$repodir/${repo%/*}"
	git-clone "$repoprefix:$repo" "$repodir/$repo"
        if [ -f "$repodir/$repo/${repo##*/}/Makefile" ] ;then
	    make -C "$repodir/$repo/${repo##*/}" update-po
	elif [ -f "$repodir/$repo/Makefile" ] ; then
	    make -C "$repodir/$repo" update-po
	else
	    fatal "Makefile for repository $repo not found"
	fi
    done

echo > $potfile
for i in $langlist; do touch $i.po; done

msgcat -o $potfile $potfile `find "$repodir" -name '*.pot'`

for i in $langlist; do
    msgcat -o $i.po $i.po `find "$repodir" -name "$i.po"`
done

rm -rf "$repodir"

./headers/po_head_repl "$potfile" ./headers/pot.header
for i in $langlist; do
    msgmerge -U $i.po "$potfile"
  ./headers/po_head_repl $i.po ./headers/$i.header
done
