#!/bin/sh -efu

. shell-error

LANGLIST="ru uk pt_BR"

print_help(){
cat <<EOF

Update desktop-file in a module directory

Usage: $0 <module directory>

EOF
}

mod_dir="${1:-}"

if [ -z "$mod_dir" ]; then
  print_help 1>&2
  exit 1
fi

name="$(sed -e '/^[[:space:]]*NAME=/!d' -e 's/NAME=//' $mod_dir/Makefile)"

[ -n "$name" ] || fatal "Can't find module name in $mod_dir/Makefile"

[ "$name" = "alterator" ] || name="alterator-$name"

echo "Updating desktop-files for $name"

dfiles="$(find "$mod_dir/applications" -name '*.desktop' 2>/dev/null ||:)"
dfiles="$dfiles $(find "$mod_dir/desktop-directories" -name '*.directory' 2>/dev/null ||:)"

[ -n "${dfiles% }" ] ||\
  fatal "Can't find $mod_dir/applications/*.desktop or $mod_dir/desktop-directories/*.directory"

for f in $dfiles; do # for each desktop file
  for v in Name Comment; do # for each field we want to translate

    # find english string in desktop-file
    str="$(sed -n "s,^$v[[:space:]]*=[[:space:]]*,,p" "$f")"
    [ -n "$str" ] || continue

    # remove old translations
    sed -i -e "/^$v\[[^]]\+\]/d" $f

    for l in $LANGLIST; do # for each language

      # translate it using po-file for this module
      tr_str="$(./utils/get_po_transl -v msgid="$str" "po/$l/$name.po")"

      if [ -n "$tr_str" ]; then
         # add \n to the tail of file if needed
         [ -z "$(tail -c1 "$f")" ] || echo >> "$f"
         # add translations
         printf '%s[%s]=%s\n' "$v" "$l" "$tr_str" >>"$f"
      else
        message "warning: can't find translation of \"$str\" for language $l"
      fi

    done
  done
done
